### ISSUE TITLE
HERE Reverse Geocoding

### ISSUE THREAD

**Issue by DenisCarriere** [DenisCarriere/geocoder#110]
From Twitter @philhubs:

@DenisCarriere With our Feb release we'll add country meta info like UTC offset, currency, dirving side, system of measure.

@DenisCarriere HERE Geocoder also offers reverse geoocoding e.g. http://t.co/TPFCgpf5QD

**Comment by DenisCarriere** [comment]
@philiphubs in your Feb release, the meta info you are talking about, is it this Map Reference?

Because other then that meta info, I don't see much extra meta included in your geocoding response.

```json
"mapReference": {
    "referenceId": "844685849", 
    "countryId": "21041602", 
    "stateId": "21041603", 
    "mapId": "NAAM14404", 
    "countyId": "21086533", 
    "cityId": "21086534", 
    "sideOfStreet": "neither", 
    "mapVersion": "Q4/2014"
}
```

**Comment by DenisCarriere** [comment]
Reverse Geocoding is now included for HERE:
Python example
```python
>>> import geocoder
>>> g = geocoder.here([45.4049053, -75.7077965], method='reverse')
>>> g.json
...
```

**Comment by philiphubs** [comment]
Hi Denis, no the meta info will be coming with the February release that is at the end of February. What is currently in production (and CIT) is the January release.
  
  
  
   Denis <notifications@github.com> hat am 3. Februar 2015 um 22:51 geschrieben:
   
   
   @philiphubs in your Feb release, the meta info you are talking about, is it this Map Reference?
   Because other then that meta info, I don't see much extra meta included in your geocoding response.
   
    "mapReference": {    "referenceId": "844685849",     "countryId": "21041602",     "stateId": "21041603",     "mapId": "NAAM14404",     "countyId": "21086533",     "cityId": "21086534",     "sideOfStreet": "neither",     "mapVersion": "Q4/2014"}

**Comment by DenisCarriere** [comment]
Ok thanks, I'll make sure to include this when the February release comes out. Thanks for the info!
