### ISSUE TITLE
Help! Not getting accurate geocodes as search in google map site

### ISSUE THREAD

**Issue by ankitissue** [DenisCarriere/geocoder#124]
g = geocoder.google('Hometown BI-LO, Hometown BI-LO, 1016 Pine Log Road, Aiken, SC 29803, United States')

g.latlng
[33.516093, -81.73750240000001]

Expected [33.523116, -81.724922]

**Comment by DenisCarriere** [comment]
I've tested your location, it seems like the issue is in Google's data, Bing & OpenStreetMap returns your expected result, and Google's result says it's 1.4km away.

The Google Maps for route navigation & Google Places API are two different databases, you should submit `Report a problem` to Google for that location.

I tested the location using the following code:
```python
import geocoder

location = '1016 Pine Log Road, Aiken, SC 29803, United States'
expected = [33.523116, -81.724922]

# Providers
bing = geocoder.bing(location)
google = geocoder.google(location)
osm = geocoder.osm(location)

# Results
print 'Google:', geocoder.distance(google.latlng, expected) * 1000, 'm'
print 'OSM:', geocoder.distance(osm.latlng, expected) * 1000, 'm'
print 'Bing:', geocoder.distance(bing.latlng, expected) * 1000, 'm'

"""
Google: 1403.55010443 m
OSM: 7.64880521966 m
Bing: 1.07508662616 m
"""
```
