### ISSUE TITLE
Clean up documentation Convert all docs to RST

### ISSUE THREAD

**Issue by DenisCarriere** [DenisCarriere/geocoder#146]
Markdown isn't cutting it anymore, can't create clean eBooks and PyPi isn't very compatible with Markdown.

**Comment by ebreton** [comment]
Hi @DenisCarriere , 

we touched this subject in a PR conversation a few days ago... the conclusion was that 

* .rst should be used for generated doc
* .md otherwise

We ideally, we would like to have the technical doc automatically generated from docstrings, but changing everything does not worth it for now.

Shall we close this issue ?

**Comment by DenisCarriere** [comment]
👍 Agreed, would be nice to generate docs from docstrings, but not worth the effort at the moment.
