### ISSUE TITLE
no module named 'geocoder'

### ISSUE THREAD

**Issue by Vcfrth** [DenisCarriere/geocoder#397]
I installed geocoder by using `git clone https://github.com/DenisCarriere/geocoder`
Now I have a Python3 file where I `import geocoder`. 
But when I run my .py file, I get "no module named 'geocoder'. 
Does anyone know what I am doing wrong? Or maybe only Python2 is supported and not Python3?
Just starting with Python on my Raspberry Pi, help would be appreciated!

**Comment by nexlabz** [comment]
You need to install the module using pip.

sudo pip install geocoder

Depending on your setup you might need to explicitly tell it to install the package for Python 3

sudo pip3 install geocoder

Then when you do your import statement  will look for the package and load. Because you are on a raspberry pi you might still need to install pip. See instructions here. https://www.raspberrypi.org/documentation/linux/software/python.md

What you are doing is cloning the geocoder repository from GitHub that contains source code. This will let you work on the code that runs geocoder.

What you want is to add the module so you can use geocoder.

**Comment by Vcfrth** [comment]
Thank you jcommaroto!  I did `sudo pip install geocoder` as well before, but it didn't work. Then I uninstalled it. I didn't know about pip3 for Python3... Still learning ;-)  `sudo pip3 install geocoder` works! 

Do you know if there is a way to UNinstall the installation of geocoder I did by using `git clone https://github.com/DenisCarriere/geocoder`? After cloning I ran `sudo python setup.py install` in the geocoder folder to install. I'm not sure if I should uninstall that one, I don't want it to interfere with the pip version of geocoder... 

Thank you!
Vc

**Comment by nexlabz** [comment]
If you do pip --version in the terminal you will likely see it is pointing to the Python 2.7 version.

That is fine, just use pip3 for everything.

If you are sure you definitely will only be building in Python3 moving forward, you can change your .bashrc folder and make the alias pip=pip3. Then from that point on every time you invoke pip you will be using pip3.

Here are raspberry pi specific directions about updating bash.
https://www.raspberrypi.org/documentation/linux/usage/bashrc.md

I wouldn't worry about removing anything the setup file did. To get rid of the local Geocoder repository just remove the folder (directory) from your system either by deleting the folder graphically or just do a rm -r geocoder (or whatever the folder is named) and you won't have to worry about it anymore.

**Comment by Vcfrth** [comment]
Thanks! I'll look into this tomorrow. Useful information. I'll remove the folder and leave the system as it is.
