### ISSUE TITLE
Rate Limit as an option instead of hardcoded

### ISSUE THREAD

**Issue by DenisCarriere** [DenisCarriere/geocoder#95]
I've created an external python script that essentially changes your IP address everytime you go over the 2500 query limit using Google, however the hardcoded Rate Limit feature prevents the script to continue even though it's not getting blocked.

Maybe having the rate limit be an option in the parameters

```python
>>> g = geocoder.google('New York city', rate_limited=True)
```
CLI
```bash
$ geocode "New York City" -p google --rate_limited
```

What are your thoughts? I'm going to `#` comment out the Rate Limited for Google for now, because it's preventing my scripts from working.

**Comment by DenisCarriere** [comment]
It's good the way it is :) I won't be changing this

**Comment by aluke1** [comment]
Rate limit should not be hardcoded.  I have unlimited requests with my google account and the rate limiter is giving me issues since I am geocoding about 50K addresses.  

I'm commenting out the rate limiter for now but it would be great if there was an option to turn it on or off.  Also, the rate limiting functionality is not well documented.  I didn't check out the source code until after spending a lot of time making sure my google account was configured correctly to allow more than 2500 requests per day. 

Thanks, 
Adam
